---
- name: Create Zabbix Template
  zabbix_template:
    login_user: Admin
    login_password: zabbix
    server_url: http://localhost/api_jsonrpc.php
    template_name: '{{ name_template }}'
    template_json:
      zabbix_export:
      date: '2018-09-24T07:44:10Z'
      version: '3.4'
      templates:
        - name: '{{ name_template }}'
          description: 'Testing template import'
          template: '{{ name_template}}'
          groups:
            - name: Templates
    template_groups: Templates
    state: present
  ignore_errors: True

- name: Import Zabbix Template
  zabbix_template:
    login_user: Admin
    login_password: zabbix
    server_url: http://localhost/api_jsonrpc.php
    template_name: '{{ name_template}}'
    template_json: "{{ lookup('template', 'zab_templ.j2') }}"
    state: present

