---
- hosts: 127.0.0.1
  tasks:


  - name: Set a macro on the Zabbix template
    local_action:
      module: zabbix_template
      server_url: http://localhost/api_jsonrpc.php
      login_user: Admin
      login_password: zabbix
      template_name: Test Template
      template_json: "{{ lookup('file', 'zab.json') }}"
      state: present
