---
- hosts: 127.0.0.1
  tasks:

# Export template json definition
    - name: Dump Zabbix template
      local_action:
        module: zabbix_template
        server_url: http://localhost/api_jsonrpc.php
        login_user: Admin
        login_password: zabbix
        template_name: Test Template
        state: dump
      register: template_dump
