---
- hosts: 127.0.0.1
  vars:
    zabbix_app:
      - { name: 'test6', name_item: 'test6i', name_key: 'net.tcp.listen[8080]' }
      - { name: 'test7', name_item: 'test7i', name_key: 'net.tcp.listen[8081]' }
      - { name: 'test8', name_item: 'test8i', name_key: 'net.tcp.listen[8082]' } 
  tasks:

    - debug: msg={{ lookup('template', 'zab_templ.j2') }}

    - template:
        src: ./zab_templ.j2
        dest: ./array.json

# Import a template from Ansible variable dict
    - name: Import Zabbix Template
      zabbix_template:
        login_user: Admin	
        login_password: zabbix
        server_url: http://localhost/api_jsonrpc.php
        template_name: Test Template
        template_json: "{{ lookup('template', 'zab_templ.j2') | to_json }}"
        state: present

